Numpy

Proceso de instalación


Creacion de arreglos a partir de listas


Con numeros prefijados


Con numeros aleatorios

In [1]:
#sentencias de importacion de input-output y google colab files
import io
from google.colab import files

In [ ]:
# El filename es el nombre del archivo.
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['Filename.csv']))

In [2]:
#importar numpy
import numpy as np


In [3]:
#crear un arreglo unidimesional
arreglo1=np.array([1,2,3,4,5])
print(arreglo1)

[1 2 3 4 5]


In [4]:
#crear arreglo de dos dimensiones
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
arreglo3=np.array([matrix, matrix])
print(arreglo3)

In [5]:
#uso de arange
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


Ejercicio:
Crear una matriz de 3 filas y 5 columnas,

 completados con los numeros del 1 al 15.


In [6]:
matriz = np.arange(1, 10).reshape(3, 3)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# creando un arreglo con 0
arreglo=np.zeros((3,5))
print(arreglo)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# hacer lo mismo pero con una matriz

In [8]:
#creando un arreglo con 1
arreglo=np.ones(10)
print(arreglo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#creando un arreglo con un mismo numero
arreglo=np.full(10,7)
print(arreglo)

[7 7 7 7 7 7 7 7 7 7]


In [11]:
#Crear un arreglo con valores uniformemente espaciados
arreglo=np.linspace(15, 20, 7)
print(arreglo)

[15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


Crear un matrix de 4 filas y 5 columnas




, lleno completamente del mismo valor 5.


# Numeros aleatorios con NumPy

In [18]:
# generar arreglo con nros enteros valor inicial,valor final, tamaño
x = np.random.randint(0,100,size=25)

print(x)


[57 30 17 26 58 20 25 75 52 47 71 47 58 92  9 94 63 45 23 27 81 79  5 91
 85]


In [19]:
#nros aleatorios entre 0 y 1
b=np.random.rand(3)
print(b)

[0.58824842 0.74934526 0.19708077]


Crear un arreglo tipo matriz de 3 filas y 7 columnas con numeros aleatorios entre 5 y 6.

# Operando sobre arreglos

In [30]:
a=np.array([1,2,3,4,5])

b=a**3

print(b)

[  1   8  27  64 125]


In [31]:
#podemos operar vectorialmente, siempre que sean de las mismos tamaños
c=np.array([6,7,8,9,10])

d=a+c

print(d)

[ 7  9 11 13 15]


### Ejersicio 1

Crear un matrix de 4 filas y 5 columnas, lleno completamente del mismo valor 5.

Solucion 1

In [15]:
arreglo=np.full(20,5)

In [13]:
arreglo.reshape(4,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

Solucion 2

In [16]:
arreglo=np.full((4,5),5)

### Ejersicio 2


Crear un arreglo tipo matriz de 5 filas y 3 columnas con numeros aleatorios entre 5 y 6.



In [29]:
x = np.random.uniform(5,6,15)
x.reshape(5,3)

array([[5.88493122, 5.66374089, 5.08734571],
       [5.87848769, 5.73749652, 5.86823158],
       [5.10747963, 5.78314602, 5.23319442],
       [5.59156099, 5.10242451, 5.35630898],
       [5.18448384, 5.64149876, 5.97762866]])

### Ejersicio 3

Crear un arreglo denominado altura de tamaño 50. Debe de generar aleatoriamente las alturas entre 1.5m y 2m.

Crear un arreglo denominado peso de tamaño 50. Debe de generar aleatoriamente los pesos entre 50kg y 100kg.

Calcular el índice de masa corporal en un tercer arreglo.

Formula de IMC tomada de: https://www.texasheart.org/heart-health/heart-information-center/topics/calculadora-del-indice-de-masa-corporal-imc/

In [44]:
peso = np.random.uniform(50,100, 50)
peso = peso.round(2)

In [45]:
altura = np.random.uniform(1.5,2, 50)
altura = altura.round(2)

In [42]:
IMC = peso / altura ** 2
IMC = IMC.round(2)

In [43]:
print(IMC)

[19.03 31.3  29.89 24.77 12.82 27.23 15.31 28.76 15.9  32.8  33.51 28.53
 16.25 29.76 25.96 21.21 25.72 20.41 35.45 27.88 32.39 24.87 20.1  25.85
 27.24 36.66 30.28 29.61 22.56 38.12 20.69 31.22 33.89 28.89 28.71 37.43
 25.36 27.89 21.5  15.68 23.65 19.64 23.62 27.93 28.99 26.78 24.42 28.42
 21.79 24.52]
